config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :cookie_rec
    end
    member do
      put :cookie_btn, to: 'posts#cookie_btn'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @email = cookies[:email]
    @_cookies = cookies
    @permission_cookies = @_cookies[:permission]


  end

  def cookie_rec
    # 쿠키 :email을 설정 (유효기간은 3개월)
    cookies[:email] = {value: params[:email],
                       expires: 1.minute.from_now,
                       http_only: true}

    respond_to do |format|
      format.html { redirect_to :back }
    end
  end

  def cookie_btn

    @_cookies = cookies
    post = Post.find(params[:id])
    permission_ids = @_cookies[:permission]
    permission_ids = [] if permission_ids.nil?

    if permission_ids.split(',').include? post.id.to_s
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { render :json => {:want_delete_count => post.delete_count,
                                       :cookies_status => '이미 클릭했습니다.'} }
      end
    else
      post.delete_count = post.delete_count + 1
      post.save

      if permission_ids == []
        permission_ids.push(post.id)
      else
        permission_ids.concat(',').concat(post.id.to_s)
      end

      @_cookies[:permission] = {value: permission_ids,
                                expires: 60.second.from_now,
                                # Time.zone.now.end_of_day
                                http_only: true}

      respond_to do |format|
        format.html { redirect_to :back }
        format.json { render :json => {:want_delete_count => post.delete_count,
                                       :cookies_status => '삭제 요청 되었습니다.'} }
      end
    end


    # cookies.signed[:comment_data] = { value: {comment_id: 1, comment_user:2}.to_yaml, expires: 2.hour.from_now }

    # if cookies[:permission_count] == 'clicked'
    #   respond_to do |format|
    #     format.html { redirect_to :back }
    #     format.json { render :json => {:want_delete_count => '이미 클릭 했습니다.'} }
    #   end
    # else
    #   cookies[:permission_count] = {value: 'clicked',
    #                                 expires: 1.minute.from_now,
    #                                 http_only: true}
    #   respond_to do |format|
    #     format.html { redirect_to :back }
    #     format.json { render :json => {:want_delete_count => '삭제 요청 되었습니다.'} }
    #   end
    # end

  end


  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @_cookies = cookies
    @permission_cookies = @_cookies[:permission]
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookiesPractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<!--교제 example-->
<!--<p>cookies test</p>-->
<%#= form_tag(action: :cookie_rec) do %>
<!--<label>메일주소:-->
<%#= text_field_tag :email, @email, size: 50 %>
<!--</label>-->
<%#= submit_tag '저장' %>
<%# end %>

<!--button 형식-->
<div>
  <h3 class="want_delete_box">
  </h3>
</div>


<table>
  <thead>
  <tr>
    <th>Email</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
      <tr>
        <td><%= post.email %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <td>
          <%= link_to cookie_btn_post_path(post), class: 'want_delete', method: :put, remote: true, data: {type: :json} do %>
              삭제요청
          <% end %> : <span class="want_delete_count"><%= post.delete_count %></span>
        </td>
        <td>
          <%= @permission_cookies %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

<script>
  $('.want_delete')
      .on('ajax:send', function () {
        $(this).addClass('loading');
      })
      .on('ajax:complete', function () {
        $(this).removeClass('loading');
      })
      .on('ajax:error', function () {
        alert('에러가 발생했습니다. 다시 시도해 보세요.');
      })
      .on('ajax:success', function (e, data, status, xhr) {
        alert(data.cookies_status);
        $(this).parent().find("span.want_delete_count").html(data.want_delete_count);
      });
</script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @post.email %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<%= link_to cookie_btn_post_path(@post), class: 'want_delete', method: :put, remote: true, data: {type: :json} do %>
    삭제요청
<% end %>
: <span class="want_delete_count"><%= @permission_cookies %></span>

<script>
  $('.want_delete')
      .on('ajax:send', function () {
        $(this).addClass('loading');
      })
      .on('ajax:complete', function () {
        $(this).removeClass('loading');
      })
      .on('ajax:error', function () {
        alert('에러가 발생했습니다. 다시 시도해 보세요.');
      })
      .on('ajax:success', function (e, data, status, xhr) {
        alert(data.cookies_status);
        $(this).parent().find("span.want_delete_count").html(data.want_delete_count);
      });
</script>